baseUrl=https://api.tst.auws.cloud/


CRFTokenEndPoint=/v2/auth/csrf
SignUpEndPoint=v2/auth/onboarding/signup
LoginEndPoint=/v2/auth/login

email=stalin.neurotrade.tst.1@mailinator.com
password=Tt123#123#
